# Handling Missing Values

In [1]:
# import libraries
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
# load the dataset
df = sns.load_dataset('titanic')
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [3]:
# check the null value
df.isnull().sum().sort_values(ascending= False)

deck           688
age            177
embarked         2
embark_town      2
sex              0
pclass           0
survived         0
fare             0
parch            0
sibsp            0
class            0
adult_male       0
who              0
alive            0
alone            0
dtype: int64

In [4]:
round(df.isnull().sum() / len (df) * 100, 4).sort_values(ascending = False)

deck           77.2166
age            19.8653
embarked        0.2245
embark_town     0.2245
sex             0.0000
pclass          0.0000
survived        0.0000
fare            0.0000
parch           0.0000
sibsp           0.0000
class           0.0000
adult_male      0.0000
who             0.0000
alive           0.0000
alone           0.0000
dtype: float64

# There are several method to fill the data
# 1. Mean , Medain, Mode
# 2. Forward and Backward imputation
# 3. Iterative Imputation
# 4. KNN Imputation (Deep Learning Techinque)

In [5]:
 # missing age data with mean
 df['age'] = df['age'].fillna(df['age'].median())

In [6]:
df.isnull().sum().sort_values(ascending = False)

deck           688
embarked         2
embark_town      2
age              0
survived         0
pclass           0
sex              0
fare             0
parch            0
sibsp            0
class            0
adult_male       0
who              0
alive            0
alone            0
dtype: int64

In [7]:
# drop the deck cloumns
df.drop('deck' , axis = 1, inplace = True)

In [8]:
df['embarked'].value_counts()

embarked
S    644
C    168
Q     77
Name: count, dtype: int64

In [9]:
# replacing embarked missing values with with mode
df['embarked'] = df['embarked'].fillna(df['embarked'].mode()[0])

In [10]:
df['embark_town'] = df['embark_town'].fillna(df['embark_town'].mode()[0])

In [11]:
df.isnull().sum()

survived       0
pclass         0
sex            0
age            0
sibsp          0
parch          0
fare           0
embarked       0
class          0
who            0
adult_male     0
embark_town    0
alive          0
alone          0
dtype: int64

## we can impute using sklearn

In [2]:
import pandas as pd
import numpy as np
import seaborn as sns

from sklearn.impute import SimpleImputer

In [3]:
df = sns.load_dataset('titanic')
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [4]:
# impute the data using simple imputer
imputer= SimpleImputer(strategy = 'median')
df['age'] = imputer.fit_transform(df[['age']])

In [9]:
df.isnull().sum().sort_values(ascending = False)

deck           688
embarked         2
embark_town      2
age              0
survived         0
pclass           0
sex              0
fare             0
parch            0
sibsp            0
class            0
adult_male       0
who              0
alive            0
alone            0
dtype: int64

# Filling value using multivariate

In [17]:
df = sns.load_dataset('titanic')

In [18]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [12]:
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
imputer = IterativeImputer()
df['age'] = imputer.fit_transform(df[['age']])

In [22]:
df.isnull().sum().sort_values(ascending=False)

deck           688
age            177
embarked         2
embark_town      2
sex              0
pclass           0
survived         0
fare             0
parch            0
sibsp            0
class            0
adult_male       0
who              0
alive            0
alone            0
dtype: int64

In [23]:
# ffill and bfill
df['age'] = df['age'].ffill()

In [24]:
df['age'] = df['age'].bfill()

In [25]:
df = sns.load_dataset('titanic')

In [26]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [27]:
from sklearn.impute import KNNImputer
imputer = KNNImputer (n_neighbors= 5)
df['age'] = imputer.fit_transform(df[['age']])