In [2]:
import pandas as pd

In [3]:

# from math import nan


data = {
    'date': ['2021-01-01', '01-02-2021', '2021/03/01', '2021.04.01'],
    'name': ['Alice da', 'alice da', 'Alice Da', 'Alice Da'],
    'country': ['USA', 'usa', 'Usa', 'USA'],
    'sales_2020': [100, None, 150, 200],
    'sales_2021': [110, 120, None, 210]
}


df = pd.DataFrame(data)

In [4]:
df.head()

         date      name country  sales_2020  sales_2021
0  2021-01-01  Alice da     USA       100.0       110.0
1  01-02-2021  alice da     usa         NaN       120.0
2  2021/03/01  Alice Da     Usa       150.0         NaN
3  2021.04.01  Alice Da     USA       200.0       210.0

In [5]:
df['date'] = pd.to_datetime(df['date'], errors='coerce')
df.head()

        date      name country  sales_2020  sales_2021
0 2021-01-01  Alice da     USA       100.0       110.0
1        NaT  alice da     usa         NaN       120.0
2        NaT  Alice Da     Usa       150.0         NaN
3        NaT  Alice Da     USA       200.0       210.0

In [6]:
# complete fill the date
df['date'] = df['date'].fillna(pd.Timestamp('2021-01-01'))
df.head()

        date      name country  sales_2020  sales_2021
0 2021-01-01  Alice da     USA       100.0       110.0
1 2021-01-01  alice da     usa         NaN       120.0
2 2021-01-01  Alice Da     Usa       150.0         NaN
3 2021-01-01  Alice Da     USA       200.0       210.0

In [8]:
df['name'] =  df['name'].replace({'Alice da':'Alice Da', 'alice da':'Alice Da' })
df.head()

        date      name country  sales_2020  sales_2021
0 2021-01-01  Alice Da     USA       100.0       110.0
1 2021-01-01  Alice Da     usa         NaN       120.0
2 2021-01-01  Alice Da     Usa       150.0         NaN
3 2021-01-01  Alice Da     USA       200.0       210.0

In [9]:
df['country'] = df['country'].replace({'usa':'USA', 'Usa':'USA'})
df.head()

        date      name country  sales_2020  sales_2021
0 2021-01-01  Alice Da     USA       100.0       110.0
1 2021-01-01  Alice Da     USA         NaN       120.0
2 2021-01-01  Alice Da     USA       150.0         NaN
3 2021-01-01  Alice Da     USA       200.0       210.0