# Feature Encoding 
Feature encoding is the process of converting categorical variables into a format that can be provided to machine learning algorithms to improve predictions. This is necessary because many machine learning algorithms require numerical input and cannot work directly with categorical data.

- one hot encoding
- label encoding
- ordinal encoding
- binary encoding

In [1]:
# import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# load the data
df = sns.load_dataset('tips')

In [3]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [4]:
df['time'].value_counts()

time
Dinner    176
Lunch      68
Name: count, dtype: int64

In [9]:
# encode the time in label encoder with sklearn
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, OrdinalEncoder
le = LabelEncoder()
df['time_le'] = le.fit_transform(df['time'])
df.head()

   total_bill   tip     sex smoker  day    time  size  time_le
0       16.99  1.01  Female     No  Sun  Dinner     2        0
1       10.34  1.66    Male     No  Sun  Dinner     3        0
2       21.01  3.50    Male     No  Sun  Dinner     3        0
3       23.68  3.31    Male     No  Sun  Dinner     2        0
4       24.59  3.61  Female     No  Sun  Dinner     4        0

In [10]:
df['day'].value_counts()

day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64

In [14]:
# label encoding the day column
oe = OrdinalEncoder(categories=[['Thur', 'Fri', 'Sat', 'Sun']])
df['day_oe'] = oe.fit_transform(df[['day']])
df.head()

   total_bill   tip     sex smoker  day    time  size  time_le  day_oe
0       16.99  1.01  Female     No  Sun  Dinner     2        0     3.0
1       10.34  1.66    Male     No  Sun  Dinner     3        0     3.0
2       21.01  3.50    Male     No  Sun  Dinner     3        0     3.0
3       23.68  3.31    Male     No  Sun  Dinner     2        0     3.0
4       24.59  3.61  Female     No  Sun  Dinner     4        0     3.0

In [18]:
df['day_oe'].value_counts()

day_oe
2.0    87
3.0    76
0.0    62
1.0    19
Name: count, dtype: int64

In [19]:
# one hot encoding the day column
ohe = OneHotEncoder()
ohe.fit_transform(df[['smoker']]).toarray()
df.head()

   total_bill   tip     sex smoker  day    time  size  time_le  day_oe
0       16.99  1.01  Female     No  Sun  Dinner     2        0     3.0
1       10.34  1.66    Male     No  Sun  Dinner     3        0     3.0
2       21.01  3.50    Male     No  Sun  Dinner     3        0     3.0
3       23.68  3.31    Male     No  Sun  Dinner     2        0     3.0
4       24.59  3.61  Female     No  Sun  Dinner     4        0     3.0

In [ ]:
# for encoding we install the category encoders library
# pip install category_encoders
# from category_encoders import BinaryEncoder, BaseNEncoder, HashingEncoder, MEstimateEncoder, TargetEncoder, CatBoostEncoder, JamesSteinEncoder

In [20]:
# use pandas for feature encoding
df = sns.load_dataset('tips')
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [23]:
pd.get_dummies(df ['day'])

      Thur    Fri    Sat    Sun
0    False  False  False   True
1    False  False  False   True
2    False  False  False   True
3    False  False  False   True
4    False  False  False   True
..     ...    ...    ...    ...
239  False  False   True  False
240  False  False   True  False
241  False  False   True  False
242  False  False   True  False
243   True  False  False  False

[244 rows x 4 columns]