# Inverse Transform / Encoding 
The inverse transform or encoding is the process of converting the transformed data back to its original form. This is typically done after applying a transformation to the data, 
- such as scaling,
- normalization,
- or encoding categorical variables. 
  The inverse transform allows us to interpret the results in the context of the original data.

- Label Encoding
- ordinal encoding
- one-hot encoding
- binary encoding

In [2]:
#import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split 
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.preprocessing import LabelEncoder, StandardScaler, OneHotEncoder , OrdinalEncoder

In [3]:
# load the data
df = sns.load_dataset('titanic')
df.head()

   survived  pclass     sex   age  ...  deck  embark_town  alive  alone
0         0       3    male  22.0  ...   NaN  Southampton     no  False
1         1       1  female  38.0  ...     C    Cherbourg    yes  False
2         1       3  female  26.0  ...   NaN  Southampton    yes   True
3         1       1  female  35.0  ...     C  Southampton    yes  False
4         0       3    male  35.0  ...   NaN  Southampton     no   True

[5 rows x 15 columns]

In [12]:
# impute missing values age, embarked, embarke_town, deck
df['age'] = df['age'].fillna(df['age'].mean())
df['embarked'] = df['embarked'].fillna(df['embarked'].mode
()[0])
df['embark_town'] = df['embark_town'].fillna(df['embark_town'].mode()[0])
df.drop('deck', axis=1, inplace=True)

In [25]:
df.isnull().sum()

survived       0
pclass         0
sex            0
age            0
sibsp          0
parch          0
fare           0
embarked       0
class          0
who            0
adult_male     0
embark_town    0
alive          0
alone          0
dtype: int64

In [26]:
# ecode the categorical variables
le_sex = LabelEncoder()
le_embarked = LabelEncoder()
le_embark_town = LabelEncoder()
le_who = LabelEncoder()
le_adult_male = LabelEncoder()
le_alive = LabelEncoder()
le_alone = LabelEncoder()
le_class = LabelEncoder()


df['sex'] = le_sex.fit_transform(df['sex'])
df['embarked'] = le_embarked.fit_transform(df['embarked'])
df['embark_town'] = le_embark_town.fit_transform(df['embark_town'])
df['who'] = le_who.fit_transform(df['who'])
df['adult_male'] = le_adult_male.fit_transform(df['adult_male'])
df['alive'] = le_alive.fit_transform(df['alive'])
df['alone'] = le_alone.fit_transform(df['alone'])
df['class'] = le_class.fit_transform(df['class'])
df.head()

   survived  pclass  sex   age  ...  adult_male  embark_town  alive  alone
0         0       3    1  22.0  ...           1            2      0      0
1         1       1    0  38.0  ...           0            0      1      0
2         1       3    0  26.0  ...           0            2      1      1
3         1       1    0  35.0  ...           0            2      1      0
4         0       3    1  35.0  ...           1            2      0      1

[5 rows x 14 columns]

In [28]:
# inverse transform the encoded variables
df['sex']=le_sex.inverse_transform(df['sex'])
df['embarked']=le_embarked.inverse_transform(df['embarked'])
df['embark_town']=le_embark_town.inverse_transform(df['embark_town'])   
df['who']=le_who.inverse_transform(df['who'])
df['adult_male']=le_adult_male.inverse_transform(df['adult_male'])
df['alive']=le_alive.inverse_transform(df['alive'])
df['alone']=le_alone.inverse_transform(df['alone'])
df['class']=le_class.inverse_transform(df['class'])

df.head()

   survived  pclass  sex   age  ...  adult_male  embark_town  alive  alone
0         0       3    1  22.0  ...           1            2      0      0
1         1       1    0  38.0  ...           0            0      1      0
2         1       3    0  26.0  ...           0            2      1      1
3         1       1    0  35.0  ...           0            2      1      0
4         0       3    1  35.0  ...           1            2      0      1

[5 rows x 14 columns]

In [29]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    int64
 3   age          891 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     891 non-null    int64
 8   class        891 non-null    int64
 9   who          891 non-null    int64
 10  adult_male   891 non-null    int64
 11  embark_town  891 non-null    int64
 12  alive        891 non-null    int64
 13  alone        891 non-null    int64
dtypes: float64(2), int64(12)
memory usage: 97.6 KB

In [42]:
df = sns.load_dataset('titanic')
df.head()

   survived  pclass     sex   age  ...  deck  embark_town  alive  alone
0         0       3    male  22.0  ...   NaN  Southampton     no  False
1         1       1  female  38.0  ...     C    Cherbourg    yes  False
2         1       3  female  26.0  ...   NaN  Southampton    yes   True
3         1       1  female  35.0  ...     C  Southampton    yes  False
4         0       3    male  35.0  ...   NaN  Southampton     no   True

[5 rows x 15 columns]

In [43]:
#one hot encode the categorical variables ang object classes
ohe_sex = OneHotEncoder()
ohe_embarked = OneHotEncoder()
ohe_embark_town = OneHotEncoder()
ohe_who = OneHotEncoder()
ohe_class = OneHotEncoder()
ohe_adult_male = OneHotEncoder()
ohe_alive = OneHotEncoder()
ohe_alone = OneHotEncoder()
df.head()

#

   survived  pclass     sex   age  ...  deck  embark_town  alive  alone
0         0       3    male  22.0  ...   NaN  Southampton     no  False
1         1       1  female  38.0  ...     C    Cherbourg    yes  False
2         1       3  female  26.0  ...   NaN  Southampton    yes   True
3         1       1  female  35.0  ...     C  Southampton    yes  False
4         0       3    male  35.0  ...   NaN  Southampton     no   True

[5 rows x 15 columns]

In [44]:
#  inverse transform the one hot encoded variables
df['sex']=ohe_sex.inverse_transform(df[['sex']])
df['embarked']=ohe_embarked.inverse_transform(df[['embarked']])
df['embark_town']=ohe_embark_town.inverse_transform(df[['embark_town']])
df['who']=ohe_who.inverse_transform(df[['who']])
df['class']=ohe_class.inverse_transform(df[['class']])
df['adult_male']=ohe_adult_male.inverse_transform(df[['adult_male']])
df['alive']=ohe_alive.inverse_transform(df[['alive']])
df['alone']=ohe_alone.inverse_transform(df[['alone']])

NotFittedError: This OneHotEncoder instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.