# Five important ways to import missing values

# 1. `Simple Imputation Methods`
- **Mean and Median Imputation**: Replace missing values with the mean or median of the column. This is suitable for numerical data that is not skewed.
- **Mode Imputation**: Replace missing values with the most frequent value in the column. This is suitable for categorical data.

# 2. `K-Nearest Neighbors (KNN) Imputation`:
- This method uses the values of the nearest neighbors to impute missing values. It can capture complex relationships in the data but can be computationally expensive.
- Example: `KNNImputer` from `sklearn` can be used for this purpose.

# 3. `Regression Imputation`:
- This method uses regression models to predict missing values based on other features in the dataset. It can be more accurate than simple imputation methods but requires careful model selection and validation.
- Example: Using `LinearRegression` from `sklearn` to predict missing values.

# 4. `Decision Tree and Random Forest Imputation`:
- These methods use decision trees or random forests to predict missing values based on other features in the dataset. They can capture complex relationships and are generally robust to outliers.
- Example: Using `DecisionTreeImputer` or `RandomForestImputer` from `sklearn` to impute missing values.    

# 5. `Advanced Imputation Methods`:
- **Multiple Imputation by Chained Equations (MICE)**: This method creates multiple imputed datasets and combines the results to account for the uncertainty in the imputations. It is suitable for complex datasets with multiple missing values.
- **Deep Learning Imputation**: Using neural networks to predict missing values based on the patterns in the data. This can be effective for large and complex datasets but requires significant computational resources.
- Example: Using libraries like `fancyimpute` for MICE or building custom neural networks for deep learning imputation. 

# 6. `Time Series Specific Imputation Methods`:
- For time series data, methods like forward fill, backward fill, and interpolation can be used to impute missing values while preserving the temporal structure of the data.
- Example: Using `pandas` methods like `fillna(method='ffill')`,
- `fillna(method='bfill')`, or `interpolate()` for time series imputation.
- These methods can help maintain the integrity of time series data while handling missing values effectively.                  
- Example: Using `pandas` methods like `fillna(method='ffill')`, `fillna(method='bfill')`, or `interpolate()` for time series imputation.

## 1. Simple Imputation Methods:
Mean and Median Imputation: Replace missing values with the mean or median of the column. This is suitable for numerical data that is not skewed.
Mode Imputation: Replace missing values with the most frequent value in the column. This is suitable for categorical data.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

#load the dataset
df = sns.load_dataset('titanic')
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [3]:
#impute the missing values
df['age'] = df['age'].fillna(df['age'].mean())
df['embarked'] = df['embarked'].fillna(df['embarked'].mode()[0])

# 2.K-Nearest Neighbors (KNN) Imputation:
This method uses the values of the nearest neighbors to impute missing values. It can capture complex
relationships in the data but can be computationally expensive.
Example: KNNImputer from sklearn can be used for this purpose.

In [4]:
df = sns.load_dataset('titanic')
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [6]:
from sklearn.impute import KNNImputer
imputer = KNNImputer(n_neighbors=5)

df['age'] = imputer.fit_transform(df[['age']])

df.isnull().sum()

survived         0
pclass           0
sex              0
age              0
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

# 3. Regression Imputation:
This method uses regression models to predict missing values based on other features in the dataset. It can
be more accurate than simple imputation methods but requires careful model selection and validation.
Example: Using LinearRegression from sklearn to predict missing values.

In [7]:
#load the dataset
df = sns.load_dataset('titanic')
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [10]:
# impute missing values with regression imputer
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer

imputer = IterativeImputer( max_iter=10, random_state=0)
df['age'] = imputer.fit_transform(df[['age']])
df.isnull().sum()

survived         0
pclass           0
sex              0
age              0
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

# 4. Random Forest Imputation:
This method uses random forests to predict missing values based on other features in the dataset. It can
capture complex relationships and is generally robust to outliers.
Example: Using RandomForestRegressor from sklearn to impute missing values.

In [11]:
# load the dataset
df = sns.load_dataset('titanic')
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [12]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.impute import SimpleImputer
from sklearn.metrics import mean_squared_error , r2_score, mean_absolute_error, accuracy_score
from sklearn.model_selection import train_test_split

In [13]:
df.drop('deck', axis=1, inplace=True)

In [17]:
from sklearn.preprocessing import LabelEncoder

#columns to encode
columns_to_encode = ['sex', 'embarked', 'class', 'who', 'alive']

label_encoders = {}

for column in columns_to_encode:

    le = LabelEncoder()

    df[column] = le.fit_transform(df[column])

    label_encoders[column] = le

    df.head()

In [18]:
df.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         0
class            0
who              0
adult_male       0
embark_town      2
alive            0
alone            0
dtype: int64

In [19]:
df_with_missing = df[df['age'].isnull()]
df_without_missing = df.dropna()

In [20]:
print('original dataset shape:', df.shape)
print('dataset with missing values shape:', df_with_missing.shape)
print('dataset without missing values shape:', df_without_missing.shape)

original dataset shape: (891, 14)
dataset with missing values shape: (177, 14)
dataset without missing values shape: (712, 14)

In [21]:
df_with_missing.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone
5,0,3,1,NaN,0,0,8.4583,1,2,1,True,Queenstown,0,True
17,1,2,1,NaN,0,0,13.0000,2,1,1,True,Southampton,1,True
19,1,3,0,NaN,0,0,7.2250,0,2,2,False,Cherbourg,1,True
26,0,3,1,NaN,0,0,7.2250,0,2,1,True,Cherbourg,0,True
28,1,3,0,NaN,0,0,7.8792,1,2,2,False,Queenstown,1,True

In [22]:
df_without_missing.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone
0,0,3,1,22.0,1,0,7.2500,2,2,1,True,Southampton,0,False
1,1,1,0,38.0,1,0,71.2833,0,0,2,False,Cherbourg,1,False
2,1,3,0,26.0,0,0,7.9250,2,2,2,False,Southampton,1,True
3,1,1,0,35.0,1,0,53.1000,2,0,2,False,Southampton,1,False
4,0,3,1,35.0,0,0,8.0500,2,2,1,True,Southampton,0,True

In [24]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df_without_missing['embark_town'] = le.fit_transform(df_without_missing['embark_town'])
X = df_without_missing.drop('age', axis=1)
y = df_without_missing['age']

x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

rf_model = RandomForestRegressor(n_estimators=100, random_state=42)
rf_model.fit(x_train, y_train)

y_pred = rf_model.predict(x_test)

print('Mean Absolute Error:', mean_absolute_error(y_test, y_pred))
print('Mean Squared Error:', mean_squared_error(y_test, y_pred))
print('R^2 Score:', r2_score(y_test, y_pred))

Mean Absolute Error: 8.485623679746332
Mean Squared Error: 134.22565123794266
R^2 Score: 0.4497841573737852